/**
 * Created by Lijingjing on 17/2/28.
 */
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const GET_TABLE_DATA_INITIATE = 'GET_TABLE_DATA_INITIATE';
export const GET_TABLE_DATA_SUCCESS = 'GET_TABLE_DATA_SUCCESS';
export const GET_TABLE_DATA_FAIL = 'GET_TABLE_DATA_FAIL';
export const UPDATE_TABLE_DATA_INITIATE = 'UPDATE_TABLE_DATA_INITIATE';
export const UPDATE_TABLE_DATA_SUCCESS = 'UPDATE_TABLE_DATA_SUCCESS';
export const UPDATE_TABLE_DATA_FAIL = 'UPDATE_TABLE_DATA_FAIL';
export const DELETE_TABLE_DATA_INITIATE = 'DELETE_TABLE_DATA_INITIATE';
export const DELETE_TABLE_DATA_SUCCESS = 'DELETE_TABLE_DATA_SUCCESS';
export const DELETE_TABLE_DATA_FAIL = 'DELETE_TABLE_DATA_FAIL';


export const SELECT_ITEM = 'SELECT_ITEM';
export const MODIFY_TABLE = 'MODIFY_TABLE';


export const DELETE_PIC = 'DELETE_PIC';
export const ADD_PIC = 'ADD_PIC';

export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const GO_PAGE = 'GO_PAGE';
export const GO_LEFT_PAGE = 'GO_LEFT_PAGE';
export const GO_RIGHT_PAGE = 'GO_RIGHT_PAGE';
export const SET_PAGE_NO = 'SET_PAGE_NO';